apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: protocol
      value: amqp
    - name: hostname
      value: rabbitmq
    - name: username
      secretKeyRef:
        name: rabbitmq-credentials
        key: username
    - name: password
      secretKeyRef:
        name: rabbitmq-credentials
        key: password
    - name: heartBeat
      value: 10s
