version: "2"

services:
  vote:
    image: vote
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: result
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: worker
    networks:
      - back-tier

  redis:
    image: armhf/redis:latest
    container_name: redis
    ports:
      - "6379"
    networks:
      - back-tier

  db:
    image: postgres:9.5
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
