version: "3"

services:
  echo:
    build: ./echo
    ports:
      - "8080:8080"
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    depends_on:
      - "worker"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    depends_on:
      - "worker"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  uploader:
    image: mayth/simple-upload-server
    ports:
      - "3000:3000"
    command:
      - "/usr/local/bin/app"
      - "-port"
      - '3000'
      - "-upload_limit"
      - '10485760'
      - "-token"
      - f9403fc5f537b4ab332d
      - "/tmp"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.6.1
    container_name: db
    ports: ["5432"]
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
