# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    type: build
    title: "Build application docker images"
    stage: "build"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    disable_push: true
    dockerfile: "Dockerfile"
    scale:
      build-vote:
        title: "Building Docker image for vote service"
        image_name: "lrochette/vote"
        working_directory: "${{clone}}/vote"
      build-result:
        title: "Building Docker image for result service"
        type: "build"
        image_name: "lrochette/result"
        working_directory: "${{clone}}/result"
      build-worker:
        title: "Building Docker image for worker service"
        type: "build"
        image_name: "lrochette/worker"
        working_directory: "${{clone}}/worker"

  BuildingTestDockerImage:
    title: Building Test Docker Image
    type: build
    stage: "build"
    image_name: lrochette/example-voting-app-tests
    working_directory: ${{clone}}/Selenium
    dockerfile: Dockerfile
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'

  # Brandon's Test

  # selenium:
  #   image: selenium/standalone-firefox:latest
  #   user: 1000:1000
  #   ports:
  #     - 4444
  #   container_name: selenium

  PostDeploymentVerificationTests:
    title: Running Selenium DVTs
    stage: "test"
    type: composition
    composition:
      version: '2'
      services:
        voting:
          image: ${{build-vote}}
          ports:
            - 80
        result:
          image: ${{build-result}}
          ports:
            - 80
        selenium-hub:
          image: selenium/hub:4.0.0-beta-3-prerelease-20210319
          container_name: selenium-hub
          ports:
            - 4444
        chrome:
          image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210319
          volumes:
            - /dev/shm
          depends_on:
            - selenium-hub
          environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
          ports:
            - 5900
    composition_candidates:
      test:
        image: ${{BuildingTestDockerImage}}
        working_dir: ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
        environment:
          VOTE_ENDPOINT_IP: voting
          RESULT_ENDPOINT_IP: result
        command: bash -c 'IFS=" " read -a browserarray <<< "${{BROWSERS}}" && for browser in "$${browserarray[@]}"; do BROWSER=$$browser python -m pytest -vvv --html=./selenium-report-$${browser}.html --self-contained-html ./tests/selenium/test_app.py; done'
        volumes:
          - '${{CF_VOLUME_NAME}}:/codefresh/volume'
    add_flow_volume_to_composition: true
    on_success:
      metadata:
        set:
          - '${{BuildingTestDockerImage.imageId}}':
              - SELENIUM_DVTS: true
    on_fail:
      metadata:
        set:
          - '${{BuildingTestDockerImage.imageId}}':
              - SELENIUM_DVTS: false
