commonLabels:
  app.kubernetes.io/name: redis

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: redis
    literals:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0