version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

orbs:
  docker: circleci/docker@2.0.1

workflows:
  build-push-vote:
    jobs:
      - docker/publish:
          name: Build Image from Pull Request and Push to Docker Hub
          filters:
            branches:
              ignore: master
          pre-steps:
            - run:
                name: Setup Environment Variables For Pull Request
                command: echo 'export TAG=uffizzi_request_`echo $CIRCLE_PULL_REQUEST | grep [^\/]*$ --only-matching`' >> $BASH_ENV
            - run:
                name: (Echo $TAG for Troubleshooting)
                command: echo $TAG
          docker-context: ./vote
          path: ./vote
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-vote
          tag: $TAG
          update-description: false
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from `master` Branch and Push to Docker Hub as `latest`
          filters:
            branches:
              only: master
          docker-context: ./vote
          path: ./vote
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-vote
          tag: latest
          update-description: true
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from Tag and Push to Docker Hub
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          docker-context: ./vote
          path: ./vote
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-vote
          tag: $CIRCLE_TAG
          update-description: false
          context:
            - test-adams-docker-hub

  build-push-result:
    jobs:
      - docker/publish:
          name: Build Image from Pull Request and Push to Docker Hub
          filters:
            branches:
              ignore: master
          pre-steps:
            - run:
                name: Setup Environment Variables For Pull Request
                command: echo 'export TAG=uffizzi_request_`echo $CIRCLE_PULL_REQUEST | grep [^\/]*$ --only-matching`' >> $BASH_ENV
            - run:
                name: (Echo $TAG for Troubleshooting)
                command: echo $TAG
          docker-context: ./result
          path: ./result
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-result
          tag: $TAG
          update-description: false
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from `master` Branch and Push to Docker Hub as `latest`
          filters:
            branches:
              only: master
          docker-context: ./result
          path: ./result
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-result
          tag: latest
          update-description: true
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from Tag and Push to Docker Hub
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          docker-context: ./result
          path: ./result
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-result
          tag: $CIRCLE_TAG
          update-description: false
          context:
            - test-adams-docker-hub

  build-push-worker:
    jobs:
      - docker/publish:
          name: Build Image from Pull Request and Push to Docker Hub
          filters:
            branches:
              ignore: master
          pre-steps:
            - run:
                name: Setup Environment Variables For Pull Request
                command: echo 'export TAG=uffizzi_request_`echo $CIRCLE_PULL_REQUEST | grep [^\/]*$ --only-matching`' >> $BASH_ENV
            - run:
                name: (Echo $TAG for Troubleshooting)
                command: echo $TAG
          docker-context: ./worker
          path: ./worker
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-worker
          tag: $TAG
          update-description: false
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from `master` Branch and Push to Docker Hub as `latest`
          filters:
            branches:
              only: master
          docker-context: ./worker
          path: ./worker
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-worker
          tag: latest
          update-description: true
          context:
            - test-adams-docker-hub

      - docker/publish:
          name: Build Image from Tag and Push to Docker Hub
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          docker-context: ./worker
          path: ./worker
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-worker
          tag: $CIRCLE_TAG
          update-description: false
          context:
            - test-adams-docker-hub
