---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../base

patches:
  - path: patch-echo.yml
    target:
      group: serving.knative.dev
      version: v1
      kind: Service
      name: echo
