apiVersion: apps/v1
#
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: lrochette/vote:latest
        name: vote
        ports:
        - containerPort: 80
