apiVersion: apps/v1
#
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: lrochette/worker:latest
        name: worker
        ports:
        - containerPort: 80
