apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: postgres
        name: postgres
        envFrom:
          - configMapRef:
              name: db
          - secretRef:
              name: db
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m" 
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
