name: CIWF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build vote image
      run: docker build -t ${DOCKER_USERNAME}/voting-app-vote:latest ./vote

    - name: Build worker image
      run: docker build -t ${DOCKER_USERNAME}/voting-app-worker:latest ./worker

    - name: Build result image
      run: docker build -t ${DOCKER_USERNAME}/voting-app-result:latest ./result

    - name: Push vote image
      run: docker push ${DOCKER_USERNAME}/voting-app-vote:latest

    - name: Push worker image
      run: docker push ${DOCKER_USERNAME}/voting-app-worker:latest

    - name: Push result image
      run: docker push ${DOCKER_USERNAME}/voting-app-result:latest

    - name: Install Sysdig CLI
      run: curl -sL https://download.sysdig.com/stable/install-sysdig | sudo bash

    - name: Scan vote image with Sysdig
      run: |
        sysdig-cli scan ${DOCKER_USERNAME}/voting-app-vote:latest
      env:
        SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}

    - name: Scan worker image with Sysdig
      run: |
        sysdig-cli scan ${DOCKER_USERNAME}/voting-app-worker:latest
      env:
        SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}

    - name: Scan result image with Sysdig
      run: |
        sysdig-cli scan ${DOCKER_USERNAME}/voting-app-result:latest
      env:
        SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
