name: build and push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build 'n push vote
        id: vote
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: vote
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          context: ./vote/
          file: ./vote/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$(date +%s)
      -
        name: build 'n push worker
        id: worker
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: worker
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          context: ./worker/
          file: ./worker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$(date +%s)
      -
        name: build 'n push result
        id: result
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: result
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          context: ./result/
          file: ./result/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$(date +%s)



    
              



          