name: build and push to dockerhub

on: [push, pull_request]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build 'n push vote
        uses: docker/build-push-action@v2
        with:
          context: ./vote/
          file: ./vote/Dockerfile
          platforms: linux/amd64
          push: true
          tags: georgerodriguex/vote:latest
      -
        name: build 'n push worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker/
          file: ./worker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: georgerodriguex/worker:latest
      -
        name: build 'n push result
        uses: docker/build-push-action@v2
        with:
          context: ./result/
          file: ./result/Dockerfile
          platforms: linux/amd64
          push: true
          tags: georgerodriguex/result:latest



    
              



          