name: Result Docker Image

on:
  push:   
    paths:
      - 'result/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: result/
        push: true
        tags: teamgrow/voting-result:${{ github.sha }},teamgrow/voting-result:latest
