name: CI S3 reusable repo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches:
  #  - master

  #pull_request:
  #  branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 'latest'

jobs:
  call-reusable-workflow:
    name: Graasp test
    uses: victorggonzalez/workflows/.github/workflows/ecs-cintegration.yml@main
    with:
      ecs-task-definition: '.aws/demo-ci.json'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER }}
      ecs-service: ${{ secrets.ECS_SERVICE }}
      container-name: ${{ secrets.CONTAINER_NAME }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY }}