name: Sysdig IaC Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Scan infrastructure
      uses: sysdiglabs/scan-action@v5
      with:
        sysdig-secure-token:  ${{ secrets.SYSDIG_SECURE_TOKEN }} #98513912-9a2c-4f60-a5ba-2c424565e793
        cli-scanner-version: 1.9.0
        mode: iac
        sysdig-secure-url: https://eu1.app.sysdig.com
        iac-scan-path: ./
