name: CI S3 reusable repo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches:
  #  - master

  #pull_request:
  #  branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # default build directory
  BUILD_FOLDER: "build"
  VERSION: "latest"

jobs:
  call-reusable-workflow:
    name: Test
    uses: victorggonzalez/workflows/.github/workflows/s3-cintegration.yml@main
    with:
      username: mona
    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
