name: Sysdig Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner" && \
        chmod +x ./sysdig-cli-scanner && \
        sudo /tmp/install-sysdig --cli

    - name: Run Sysdig CLI Scanner
      env:
        SYSDIG_SECURE_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        SECURE_API_TOKEN=SYSDIG_SECURE_TOKEN ./sysdig-cli-scanner --iac --apiurl https://eu1.app.sysdig.com ./
        
